name: Release Tag

permissions:
  contents: write

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
      - master

jobs:
  create_tag:
    if: startsWith(github.head_ref, 'release-')
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.set_tag_name.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v3

      - name: Extract version
        id: extract_version
        run: echo "VERSION=$(echo ${GITHUB_HEAD_REF#release-})" >> $GITHUB_ENV

      - name: Create tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch --all
          git tag $VERSION
          git push origin $VERSION
        env:
         VERSION: ${{ env.VERSION }}

      - name: Set tag name output
        id: set_tag_name
        run: echo "tag_name=${{ env.VERSION }}" >> $GITHUB_OUTPUT


  build_and_release:
    name: Build and Draft Release
    needs: create_tag  # This makes sure this job runs after create_tag finishes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go (read version from go.mod)
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod  # This tells the action to use the Go version in go.mod

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -ldflags "-X 'github.com/pezhmankasraee/pksetdev/help.Version=$(git describe --tags --dirty --always)'" -o pksetdev-linux

      - name: Compress Linux binary
        run: |
          tar -czvf pksetdev-linux.tar.gz pksetdev-linux
          zip pksetdev-linux.zip pksetdev-linux

      - name: Build for MacOS
        run: |
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X 'github.com/pezhmankasraee/pksetdev/help.Version=$(git describe --tags --dirty --always)'" -o pksetdev-darwin

      - name: Compress MacOS binary
        run: |
          tar -czvf pksetdev-darwin.tar.gz pksetdev-darwin
          zip pksetdev-darwin.zip pksetdev-darwin

      - name: Compress source code
        run: |
          git archive --format=tar.gz -o source.tar.gz HEAD
          git archive --format=zip -o source.zip HEAD


  create_draft_release:
    needs: create_tag
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create draft release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.create_tag.outputs.tag_name }}
          release_name: ${{ needs.create_tag.outputs.tag_name }}
          draft: true
          prerelease: false


  upload_assets:
    needs: create_draft_release
    runs-on: ubuntu-latest
    steps:
       # Download artifacts or checkout code as needed
      - name: Upload Linux tar.gz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft_release.outputs.upload_url }}
          asset_path: ./pksetdev-linux.tar.gz
          asset_name: pksetdev-linux.tar.gz
          asset_content_type: application/gzip
      - name: Upload Linux zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft_release.outputs.upload_url }}
          asset_path: ./pksetdev-linux.zip
          asset_name: pksetdev-linux.zip
          asset_content_type: application/zip
      - name: Upload MacOS tar.gz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft_release.outputs.upload_url }}
          asset_path: ./pksetdev-darwin.tar.gz
          asset_name: pksetdev-darwin.tar.gz
          asset_content_type: application/gzip
      - name: Upload MacOS zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft_release.outputs.upload_url }}
          asset_path: ./pksetdev-darwin.zip
          asset_name: pksetdev-darwin.zip
          asset_content_type: application/zip
      - name: Upload source tar.gz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft_release.outputs.upload_url }}
          asset_path: ./source.tar.gz
          asset_name: source.tar.gz
          asset_content_type: application/gzip
      - name: Upload source zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft_release.outputs.upload_url }}
          asset_path: ./source.zip
          asset_name: source.zip
          asset_content_type: application/zip