name: Release Tag

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
      - master

jobs:
  create_tag:
    if: startsWith(github.head_ref, 'release-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract version
        id: extract_version
        run: echo "VERSION=$(echo ${GITHUB_HEAD_REF#release-})" >> $GITHUB_ENV

      - name: Create tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch --all
          git tag $VERSION
          git push origin $VERSION
        env:
          VERSION: ${{ env.VERSION }}
